from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("set-role/", views.set_role, name="set_role"),
    path("leads/", views.lead_list, name="lead_list"),
    path("leads/add/", views.lead_create, name="lead_create"),
    path("leads/<int:pk>/edit/", views.lead_update, name="lead_update"),
    path("leads/<int:pk>/progress/", views.lead_progress, name="lead_progress"),
    path("leads/<int:pk>/delete/", views.lead_delete, name="lead_delete"),
    path("properties/", views.property_list, name="property_list"),
    path("properties/add/", views.property_create, name="property_create"),
    path("properties/<int:pk>/edit/", views.property_update, name="property_update"),
    path("properties/<int:pk>/delete/", views.property_delete, name="property_delete"),
    path("clients/", views.client_list, name="client_list"),
    path("clients/add/", views.client_create, name="client_create"),
    path("clients/<int:pk>/edit/", views.client_update, name="client_update"),
    path("clients/<int:pk>/delete/", views.client_delete, name="client_delete"),
    path("deals/", views.deal_list, name="deal_list"),
    path("deals/add/", views.deal_create, name="deal_create"),
    path("deals/<int:pk>/edit/", views.deal_update, name="deal_update"),
    path("deals/<int:pk>/stage/<str:stage>/", views.deal_stage, name="deal_stage"),
    path("deals/<int:pk>/delete/", views.deal_delete, name="deal_delete"),
    path("deals/<int:pk>/documents/", views.document_upload, name="document_upload"),
    path("communications/", views.communications, name="communications"),
    path("communications/activity/", views.activity_create, name="activity_create"),
    path("communications/reminder/", views.reminder_create, name="reminder_create"),
    path("communications/reminders/<int:pk>/toggle/", views.reminder_toggle, name="reminder_toggle"),
    path("agents/", views.agent_list, name="agent_list"),
    path("agents/add/", views.agent_create, name="agent_create"),
    path("agents/<int:pk>/edit/", views.agent_update, name="agent_update"),
    path("agents/<int:pk>/delete/", views.agent_delete, name="agent_delete"),
    path("reports/", views.reports, name="reports"),
    path("reports/export/csv/", views.export_csv, name="export_csv"),
    path("reports/export/pdf/", views.export_pdf, name="export_pdf"),
    path("integrations/", views.integrations, name="integrations"),
    path("integrations/website-capture/", views.website_capture, name="website_capture"),
    path("api/leads/capture/", views.api_lead_capture, name="api_lead_capture"),
    path("api/webhooks/lead/", views.api_lead_capture, name="api_lead_webhook"),
]
