# Generated by Django 5.2.4 on 2026-04-27 18:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Agent', 'Agent')], default='Agent', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('client_type', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Buyer', max_length=20)),
                ('preferences', models.TextField(blank=True)),
                ('inquiries', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('deal', 'Deal')], default='lead', max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('Call', 'Call'), ('SMS', 'SMS'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Meeting', 'Meeting')], default='Call', max_length=20)),
                ('direction', models.CharField(choices=[('Inbound', 'Inbound'), ('Outbound', 'Outbound')], default='Outbound', max_length=20)),
                ('note', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('stage', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Negotiation', 'Negotiation'), ('Agreement', 'Agreement'), ('Closed', 'Closed')], default='Inquiry', max_length=30)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_close', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('Website', 'Website'), ('Ads', 'Ads'), ('Calls', 'Calls'), ('Referral', 'Referral'), ('Portal', 'Portal')], default='Manual', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preferences', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Closed', 'Closed'), ('Lost', 'Lost')], default='New', max_length=30)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='client',
            name='linked_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.lead'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=30)),
                ('location', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('size', models.CharField(blank=True, max_length=80)),
                ('amenities', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='properties/')),
                ('image_url', models.URLField(blank=True)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Under Offer', 'Under Offer'), ('Sold', 'Sold')], default='Available', max_length=30)),
                ('map_query', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='crm.agent')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.property'),
        ),
        migrations.AddField(
            model_name='client',
            name='visited_properties',
            field=models.ManyToManyField(blank=True, related_name='visitors', to='crm.property'),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('deal', 'Deal')], default='lead', max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('channel', models.CharField(choices=[('Call', 'Call'), ('SMS', 'SMS'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Meeting', 'Meeting')], default='Call', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='crm.agent')),
            ],
            options={
                'ordering': ['completed', 'due_date'],
            },
        ),
    ]
